### ISSUE TITLE
about handling of the symbolic memory access

### ISSUE THREAD

**Issue by moliam** [S2E/libs2ecore#8]
It seems that when the address of load/store operation is symbolic, s2e would invoke the handleForkAndConcretize function to evaluate a concrete example of the symb addr and fork another state, and then in both states the memory address are concretized. However, I suppose, this may lead to some loss of symbolic information( loss of logical space ), and may result to failure of constaint solving in some circumstances.   But I find that using the original method that klee adopts for handling symbolic address is not suitable for the situation of s2e.  So is handleForAndConcretize a compromised solution?  
Thanks a lot!

**Comment by vitalych** [comment]
handleForkAndConcretize should lazily evaluate all concrete values of the symbolic pointer, so there shouldn't be loss of completeness.

One state will have x==1, the other will have x!=1, which is still symbolic.
https://github.com/S2E/libs2ecore/blob/master/src/S2EExecutor.cpp#L640

**Comment by moliam** [comment]
@vitalych  Thank you very much.  So in the original klee, symbolic address access can be condensed into one symbolic Expr and one execution state; whereas in s2e all memory addrs in the Expr are concrete, and all the possible concrete values of symbolic mem address are lazily evaluated and explored via forking corresponding number of execution states.  Do I understand right?

**Comment by vitalych** [comment]
S2E can also support symbolic addresses, but partially. Only the lowest 12 bits can be symbolic because of TLB issues. There is a switch to enable/disable this mode.

**Comment by adrianherrera** [comment]
Which switch is that?

**Comment by vitalych** [comment]
https://github.com/S2E/libs2ecore/blob/master/src/S2EExecutor.cpp#L109
